builds:
- main: ./cmd/discover/main.go
  binary: discover
  goos:
    - linux
  goarch:
    - amd64
    - arm64
    - arm
    - 386
archives:
- id: default
  format: zip
  files:
  - none*
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
